name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "e7e859ec-fd3e-4600-a19f-1aa5390064b6"      # 替换为你创建的数据库 ID
